name       : pulseaudio-dlna
version    : 0.5.2
release    : 1
source     :
    - https://github.com/masmu/pulseaudio-dlna/archive/0.5.2.tar.gz : e07f6db31502d90f6f8971d2cd1f96a540e2bd7f26f0090afdaee5b5c73f6a68
license    : GPL-3.0
component  : multimedia.audio
summary    : A lightweight streaming server which brings DLNA / UPNP and Chromecast support to PulseAudio and Linux
description: |
    A lightweight streaming server which brings DLNA / UPNP and Chromecast support to PulseAudio and Linux. It can stream your current PulseAudio playback to different UPNP devices (UPNP Media Renderers) or Chromecasts in your network.
builddeps  :
    - python-setuptools
rundeps    :
    - python-chardet
    - python-docopt
    - python-enum-compat
    - python-futures
    - python-lxml
    - python-netaddr
    - python-netifaces
    - python-notify2
    - python-protobuf
    - python-psutil
    - python-setproctitle
    - python-zeroconf
build      : |
    %python_setup
install    : |
    %python_install
